apiVersion: app/v1
kind: Replica
metadata:
  name: myfirstpod
  labels:
    app: flask
spec:
  template:
    metadata:
      name: myfirstpod
      labels:
        app: flask
    spec:
      containers:
        - name : myfirstpod
        image: teja1521/dev_python
 replicas: 3
 selector:
  matchLabels:
    app: flask
